package com.elpinho.seekerdrones.client;

import com.elpinho.seekerdrones.SeekerDrones;
import com.elpinho.seekerdrones.drone.DroneEntity;
import com.mojang.blaze3d.vertex.PoseStack;
import com.mojang.blaze3d.vertex.VertexConsumer;

import net.minecraft.client.model.EntityModel;
import net.minecraft.client.model.geom.ModelLayerLocation;
import net.minecraft.client.model.geom.ModelPart;
import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;
import net.minecraft.client.renderer.texture.OverlayTexture;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.util.FastColor;
import net.minecraft.util.Mth;

/**
 * Quadcopter drone model: a central body with a front lens, two diagonal arms forming an X, a motor and a spinning
 * rotor at each corner (the frame), plus a canopy on top of the body (the shell) tinted with the drone's color.
 * The texture is generated by {@code scripts/textures/generate_textures.py}, which mirrors the UV layout below.
 */
public class DroneModel extends EntityModel<DroneEntity> {
    public static final ModelLayerLocation LAYER =
            new ModelLayerLocation(ResourceLocation.fromNamespaceAndPath(SeekerDrones.MODID, "drone"), "main");

    /** Distance of each rotor's center from the body's center along X and Z, in model pixels. */
    private static final float ROTOR_OFFSET = 6;
    /** Rotor spin in radians per tick. Diagonal pairs spin in opposite directions, like a real quadcopter. */
    private static final float ROTOR_SPEED = 1.95F;
    private static final String[] ROTORS = {"rotor_front_left", "rotor_front_right", "rotor_back_left", "rotor_back_right"};

    private final ModelPart frame;
    private final ModelPart shell;
    private final ModelPart[] rotors = new ModelPart[ROTORS.length];
    private int tint = -1;

    public DroneModel(ModelPart root) {
        this.frame = root.getChild("frame");
        this.shell = root.getChild("shell");
        for (int i = 0; i < ROTORS.length; i++) {
            rotors[i] = frame.getChild(ROTORS[i]);
        }
    }

    public static LayerDefinition createBodyLayer() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();

        CubeListBuilder frameCubes = CubeListBuilder.create()
                .texOffs(0, 0).addBox(-3, 0, -3, 6, 2, 6)
                .texOffs(40, 0).addBox(-1, 0.5F, -4, 2, 1, 1);
        for (float x : new float[] {-ROTOR_OFFSET, ROTOR_OFFSET}) {
            for (float z : new float[] {-ROTOR_OFFSET, ROTOR_OFFSET}) {
                frameCubes.texOffs(36, 8).addBox(x - 1, -1, z - 1, 2, 2, 2);
            }
        }
        PartDefinition frame = root.addOrReplaceChild("frame", frameCubes, PartPose.offset(0, 20, 0));

        // Each arm links two opposite motors (2 * ROTOR_OFFSET * sqrt(2) ~ 17 pixels), rotated 45 degrees to reach
        // the corners.
        for (int i = 0; i < 2; i++) {
            frame.addOrReplaceChild("arm_" + i, CubeListBuilder.create()
                            .texOffs(0, 8).addBox(-8.5F, 0.5F, -0.5F, 17, 1, 1),
                    PartPose.rotation(0, (i == 0 ? 1 : -1) * Mth.HALF_PI / 2, 0));
        }

        // Flat rotors: the entity render type doesn't cull, so the top face is seen from below too. The bottom face
        // is transparent in the texture, since it would z-fight with the top one. They float above the motors to
        // avoid z-fighting with them as well.
        for (int i = 0; i < ROTORS.length; i++) {
            float x = i % 2 == 0 ? -ROTOR_OFFSET : ROTOR_OFFSET;
            float z = i < 2 ? -ROTOR_OFFSET : ROTOR_OFFSET;
            frame.addOrReplaceChild(ROTORS[i], CubeListBuilder.create()
                            .texOffs(0, 12).addBox(-3, 0, -3, 6, 0, 6),
                    PartPose.offset(x, -1.5F, z));
        }

        root.addOrReplaceChild("shell", CubeListBuilder.create()
                        .texOffs(24, 0).addBox(-2, -1, -2, 4, 1, 4),
                PartPose.offset(0, 20, 0));
        return LayerDefinition.create(mesh, 64, 32);
    }

    @Override
    public void setupAnim(DroneEntity entity, float limbSwing, float limbSwingAmount, float ageInTicks, float netHeadYaw, float headPitch) {
        tint = FastColor.ARGB32.opaque(entity.getColor().getTextureDiffuseColor());
        float spin = ageInTicks * ROTOR_SPEED;
        for (int i = 0; i < rotors.length; i++) {
            // Front left and back right spin one way, front right and back left the other.
            boolean clockwise = i == 0 || i == 3;
            rotors[i].yRot = (clockwise ? spin : -spin) + i;
        }
    }

    @Override
    public void renderToBuffer(PoseStack poseStack, VertexConsumer buffer, int packedLight, int packedOverlay, int color) {
        // Ignore packedOverlay: drones don't get the vanilla red hurt flash (DESIGN.md section 2.5).
        frame.render(poseStack, buffer, packedLight, OverlayTexture.NO_OVERLAY, color);
        shell.render(poseStack, buffer, packedLight, OverlayTexture.NO_OVERLAY, FastColor.ARGB32.multiply(color, tint));
    }
}
