package com.elpinho.seekerdrones.datagen;

import com.elpinho.seekerdrones.SeekerDrones;
import com.elpinho.seekerdrones.deploying.DeployingStatus;
import com.elpinho.seekerdrones.drone.DroneState;
import com.elpinho.seekerdrones.drone.UpgradeType;
import com.elpinho.seekerdrones.energy.EnergyUnit;
import com.elpinho.seekerdrones.factory.FactorySlots;
import com.elpinho.seekerdrones.factory.FactoryStatus;
import com.elpinho.seekerdrones.network.StationStatusPayload;
import com.elpinho.seekerdrones.registry.ModBlocks;
import com.elpinho.seekerdrones.registry.ModEntityTypes;
import com.elpinho.seekerdrones.registry.ModItems;

import net.minecraft.data.PackOutput;
import net.neoforged.neoforge.common.data.LanguageProvider;

public class ModLanguageProvider extends LanguageProvider {
    public ModLanguageProvider(PackOutput output) {
        super(output, SeekerDrones.MODID, "en_us");
    }

    @Override
    protected void addTranslations() {
        add("itemGroup.seekerdrones", "Seeker Drones");

        addItem(ModItems.DRONE, "Drone");
        addEntityType(ModEntityTypes.DRONE, "Drone");
        addBlock(ModBlocks.CHARGING_STATION, "Drone Charging Station");
        addBlock(ModBlocks.DRONE_FACTORY, "Drone Factory");
        addBlock(ModBlocks.PROGRAMMING_STATION, "Drone Programming Station");
        addBlock(ModBlocks.DEPLOYING_STATION, "Drone Deploying Station");
        add("tooltip.seekerdrones.deploying_station.auto_deploy_off", "Auto-deploy: Off");
        add("tooltip.seekerdrones.machine_upgrades", "%s Upgrades: %s");
        add("screen.seekerdrones.energy", "Energy");
        add("screen.seekerdrones.deploying_station", "Deploying Station");
        add("screen.seekerdrones.deploying_station.auto_deploy", "Auto-deploy");
        add("screen.seekerdrones.deploying_station.auto_deploy.tooltip", "Auto: deploys every inserted drone as soon as possible.\nManual: the Deploy button or a redstone pulse deploys.");
        add("screen.seekerdrones.deploying_station.auto", "Auto");
        add("screen.seekerdrones.deploying_station.manual", "Man");
        add("screen.seekerdrones.deploying_station.deploy", "Deploy");
        add("screen.seekerdrones.deploying_station.deploy.tooltip", "Launches the drone now");
        add("screen.seekerdrones.deploying_station.deploy.auto", "Auto-deploy is on");
        add("screen.seekerdrones.deploying_station.deploy.open_cover", "Click the cover to switch to manual");
        add("screen.seekerdrones.deploying_station.energy_per_deploy", "%s per deploy");
        add("screen.seekerdrones.deploying_station.redstone", "Redstone");
        add("screen.seekerdrones.deploying_station.redstone.manual", "Manual mode: a pulse deploys");
        add("screen.seekerdrones.deploying_station.redstone.auto", "Ignored while Auto is on");
        add("screen.seekerdrones.deploying_station.redstone.signal", "Signal: %s");
        add("screen.seekerdrones.deploying_station.redstone.on", "On");
        add("screen.seekerdrones.deploying_station.redstone.off", "Off");
        add(DeployingStatus.IDLE.getHintKey(), "insert a drone");
        add(DeployingStatus.READY.getHintKey(), "press Deploy");
        add(DeployingStatus.NO_ENERGY.getHintKey(), "needs %s per deploy");
        add(DeployingStatus.BLOCKED.getHintKey(), "clear the space above the station");
        add(DeployingStatus.IDLE.getTranslationKey(), "No drone");
        add(DeployingStatus.READY.getTranslationKey(), "Ready");
        add(DeployingStatus.NO_ENERGY.getTranslationKey(), "Not enough energy");
        add(DeployingStatus.BLOCKED.getTranslationKey(), "Space above blocked");
        add("tooltip.seekerdrones.programming_station.programmed", "Programmed (%s)");
        add("screen.seekerdrones.programming_station", "Programming Station");
        add("screen.seekerdrones.programming_station.mode", "Mode");
        add("screen.seekerdrones.programming_station.mode.direct", "Direct");
        add("screen.seekerdrones.programming_station.mode.template", "Template");
        add("screen.seekerdrones.programming_station.mode.tooltip", "Direct: edit the drone in the slot by hand.\nTemplate: bring every inserted drone to the stored program. Automation can pull complete drones out.");
        add("screen.seekerdrones.programming_station.help", "How it works");
        add("screen.seekerdrones.programming_station.help.direct", "Direct: edit the drone in the slot. Left-click an upgrade to install one from the input, right-click to remove one.");
        add("screen.seekerdrones.programming_station.help.template", "Template: save a program. Every drone inserted is brought to match it, and automation can pull complete drones out.");
        add("screen.seekerdrones.programming_station.tab.upgrades", "Upgrades");
        add("screen.seekerdrones.programming_station.tab.targets", "Targets");
        add("screen.seekerdrones.programming_station.tab.behavior", "Behavior");
        add("screen.seekerdrones.programming_station.tab.identity", "Identity");
        add("screen.seekerdrones.programming_station.no_drone", "Insert a drone to edit it.");
        add("screen.seekerdrones.programming_station.loading", "Loading...");
        add("screen.seekerdrones.programming_station.bay", "Drone preview");
        add("screen.seekerdrones.programming_station.bay.patrol", "Circles its patrol radius: %s of max %s blocks");
        add("screen.seekerdrones.programming_station.bay.hover", "Hovers in place: no Patrol upgrade");
        add("screen.seekerdrones.programming_station.bay.preview", "A preview, not the drone's real position");
        add("screen.seekerdrones.programming_station.slot.drone", "Drone slot");
        add("screen.seekerdrones.programming_station.slot.drone.tooltip", "Insert a drone to edit or program it");
        add("screen.seekerdrones.programming_station.slot.input", "%s upgrade input");
        add("screen.seekerdrones.programming_station.slot.input.tooltip", "Only takes %s upgrades");
        add("screen.seekerdrones.programming_station.slots", "Upgrade slots");
        add("screen.seekerdrones.programming_station.slots.used", "%s / %s used");
        add("screen.seekerdrones.programming_station.upgrade.installed", "Installed: %s / %s");
        add("screen.seekerdrones.programming_station.upgrade.programmed", "Programmed: %s");
        add("screen.seekerdrones.programming_station.upgrade.in_input", "In input: %s");
        add("screen.seekerdrones.programming_station.upgrade.cost", "Next install: %s");
        add("screen.seekerdrones.programming_station.upgrade.installing", "Installing: %s%%");
        add("screen.seekerdrones.programming_station.upgrade.extra", "Extra: %s more than the program. Shift+right-click removes one (it goes into your inventory).");
        add("screen.seekerdrones.programming_station.upgrade.hint.direct", "Left-click: install one from the input. Right-click: remove one (it goes into your inventory).");
        add("screen.seekerdrones.programming_station.upgrade.hint.template", "Left-click: add one to the program. Right-click: take one out.");
        add("screen.seekerdrones.programming_station.target.slots", "%s / %s slots");
        add("screen.seekerdrones.programming_station.target.value", "Target");
        add("screen.seekerdrones.programming_station.target.kind", "Kind: %s");
        add("screen.seekerdrones.programming_station.target.kind.tooltip", "Click to change");
        add("screen.seekerdrones.programming_station.target.add", "+ add target");
        add("screen.seekerdrones.programming_station.target.empty", "Empty target slot");
        add("screen.seekerdrones.programming_station.target.select", "Click to select and type to edit");
        add("screen.seekerdrones.programming_station.target.hint", "Type to search. Tab accepts a suggestion.");
        add("screen.seekerdrones.programming_station.target.none", "Empty");
        add("screen.seekerdrones.programming_station.target.preview", "Preview");
        add("screen.seekerdrones.programming_station.target.remove", "Remove this target");
        add("screen.seekerdrones.programming_station.target.duplicate", "%s is already a target");
        add("screen.seekerdrones.programming_station.target.unknown.entity_type", "Unknown entity type: %s");
        add("screen.seekerdrones.programming_station.target.unknown.tag", "Unknown entity tag: %s");
        add("screen.seekerdrones.programming_station.target.unknown.player_name", "Invalid player name: %s");
        add("screen.seekerdrones.programming_station.target.no_slot", "No free target slot");
        add("screen.seekerdrones.programming_station.target.needs_player_seek", "Player targets need Player Seek");
        add("screen.seekerdrones.programming_station.target.ignored.no_slot", "Ignored: no free target slot");
        add("screen.seekerdrones.programming_station.target.ignored.player_seek", "Ignored: needs Player Seek");
        add("screen.seekerdrones.programming_station.target.blacklisted", "%s is blacklisted on this server");
        add("screen.seekerdrones.programming_station.target.ignored.blacklisted", "Ignored: blacklisted on this server");
        add("screen.seekerdrones.programming_station.follow_distance", "Follow distance");
        add("screen.seekerdrones.programming_station.follow_distance.header", "Follow distance (blocks)");
        add("screen.seekerdrones.programming_station.follow_distance.tooltip", "Blocks kept from the target while following (%s-%s)");
        add("screen.seekerdrones.programming_station.follow_distance.invalid", "The follow distance must be %s-%s");
        add("screen.seekerdrones.programming_station.label", "Label");
        add("screen.seekerdrones.programming_station.label.hint", "None");
        add("screen.seekerdrones.programming_station.color", "Color");
        add("screen.seekerdrones.programming_station.nameplate", "Nameplate");
        add("screen.seekerdrones.programming_station.nameplate.no_label", "No label");
        add("screen.seekerdrones.programming_station.patrol.none", "Patrol settings need a Patrol upgrade.");
        add("screen.seekerdrones.programming_station.patrol_center", "Patrol center");
        add("screen.seekerdrones.programming_station.patrol_center.here", "Here");
        add("screen.seekerdrones.programming_station.patrol_center.here.tooltip", "Use the block above this station");
        add("screen.seekerdrones.programming_station.patrol_center.clear", "Clear");
        add("screen.seekerdrones.programming_station.patrol_center.clear.tooltip", "No patrol center: the drone patrols around where it came to rest");
        add("screen.seekerdrones.programming_station.patrol_radius", "Patrol radius");
        add("screen.seekerdrones.programming_station.patrol_radius.header", "Patrol radius · max %s");
        add("screen.seekerdrones.programming_station.patrol_radius.slider", "Drag to set it (1-%s blocks)");
        add("screen.seekerdrones.programming_station.patrol_radius.tooltip", "Empty: the largest the Patrol upgrades allow (%s)");
        add("screen.seekerdrones.programming_station.patrol_radius.invalid", "The patrol radius must be at least 1");
        add("screen.seekerdrones.programming_station.patrol_speed", "Patrol speed");
        add("screen.seekerdrones.programming_station.patrol_speed.header", "Patrol speed · max %s blocks/s");
        add("screen.seekerdrones.programming_station.patrol_speed.slider", "Drag to set it (0.2-%s blocks/second)");
        add("screen.seekerdrones.programming_station.patrol_speed.tooltip", "Empty: the base patrol speed (%s), however many Patrol upgrades");
        add("screen.seekerdrones.programming_station.patrol_speed.invalid", "The patrol speed must be at least 0.2 blocks/second");
        add("screen.seekerdrones.programming_station.status.insert_drone", "Insert a drone to edit it.");
        add("screen.seekerdrones.programming_station.status.insert_drone_template", "Insert a drone to program it.");
        add("screen.seekerdrones.programming_station.status.direct_hint", "Put upgrades in the input and click their tiles to install them.");
        add("screen.seekerdrones.programming_station.status.installing", "Installing %s: %s%% (%s)");
        add("screen.seekerdrones.programming_station.status.no_power", "Not enough energy to install %s");
        add("screen.seekerdrones.programming_station.status.template_invalid", "The program exceeds the upgrade limits");
        add("screen.seekerdrones.programming_station.status.extra_upgrades", "Remove extra upgrades: %s");
        add("screen.seekerdrones.programming_station.status.missing_upgrades", "Waiting for upgrades: %s");
        add("screen.seekerdrones.programming_station.status.complete", "Complete: ready to be taken out");
        add("screen.seekerdrones.programming_station.status.reinsert_drone", "This drone was here before Template mode. Re-insert it to program it.");
        add("screen.seekerdrones.programming_station.status.working", "Programming...");
        addItem(ModItems.DRONE_ROTOR, "Drone Rotor");
        addItem(ModItems.SEEKER_CORE, "Seeker Core");

        add("tooltip.seekerdrones.drone.unassigned", "Unassigned");
        add("tooltip.seekerdrones.drone.owner", "Owner: %s");
        add("tooltip.seekerdrones.drone.energy", "Energy: %s");
        add("tooltip.seekerdrones.drone.health", "Health: %s / %s");
        add("tooltip.seekerdrones.drone.upgrades", "Upgrades:");
        add("tooltip.seekerdrones.drone.upgrade_entry", "%s x%s");
        add("tooltip.seekerdrones.drone.targets", "Targets: %s");

        add(UpgradeType.PATROL.getTranslationKey(), "Patrol");
        add(UpgradeType.SIGHT.getTranslationKey(), "Sight");
        add(UpgradeType.EXPLOSIVE.getTranslationKey(), "Explosive");
        add(UpgradeType.SIREN.getTranslationKey(), "Siren");
        add(UpgradeType.TRANSMITTER.getTranslationKey(), "Transmitter");
        add(UpgradeType.ENERGY.getTranslationKey(), "Energy");
        add(UpgradeType.HEALTH.getTranslationKey(), "Health");
        add(UpgradeType.PLAYER_SEEK.getTranslationKey(), "Player Seek");

        addItem(ModItems.upgrade(UpgradeType.PATROL), "Patrol Upgrade");
        addItem(ModItems.upgrade(UpgradeType.SIGHT), "Sight Upgrade");
        addItem(ModItems.upgrade(UpgradeType.EXPLOSIVE), "Explosive Upgrade");
        addItem(ModItems.upgrade(UpgradeType.SIREN), "Siren Upgrade");
        addItem(ModItems.upgrade(UpgradeType.TRANSMITTER), "Transmitter Upgrade");
        addItem(ModItems.upgrade(UpgradeType.ENERGY), "Energy Upgrade");
        addItem(ModItems.upgrade(UpgradeType.HEALTH), "Health Upgrade");
        addItem(ModItems.upgrade(UpgradeType.PLAYER_SEEK), "Player Seek Upgrade");

        add(UpgradeType.PATROL.getTranslationKey() + ".description", "Patrols in a circle around its patrol center.");
        add(UpgradeType.SIGHT.getTranslationKey() + ".description", "Increases the range at which targets are spotted.");
        add(UpgradeType.EXPLOSIVE.getTranslationKey() + ".description", "Explodes on reaching its target.");
        add(UpgradeType.SIREN.getTranslationKey() + ".description", "Sounds a siren when a target is spotted.");
        add(UpgradeType.TRANSMITTER.getTranslationKey() + ".description", "Tells the drone's online operators when a target is spotted.");
        add(UpgradeType.ENERGY.getTranslationKey() + ".description", "Doubles max energy.");
        add(UpgradeType.HEALTH.getTranslationKey() + ".description", "Increases max health.");
        add(UpgradeType.PLAYER_SEEK.getTranslationKey() + ".description", "Allows setting players as targets.");
        add("tooltip.seekerdrones.upgrade.max_count", "Max per drone: %s");

        add("subtitles.seekerdrones.drone_siren", "Drone siren blares");
        add("subtitles.seekerdrones.drone_fly", "Drone whirs");
        add("subtitles.seekerdrones.drone_deploy", "Drone spins up");
        add("subtitles.seekerdrones.drone_hurt", "Drone hurts");
        add("subtitles.seekerdrones.drone_destroy", "Drone breaks");
        add("subtitles.seekerdrones.drone_low_power", "Drone beeps low battery");
        add("subtitles.seekerdrones.drone_low_power_critical", "Drone beeps urgently");
        add("subtitles.seekerdrones.drone_lock_on", "Drone locks on");
        add("subtitles.seekerdrones.drone_target_lost", "Drone loses target");
        add("subtitles.seekerdrones.drone_charged", "Drone chirps");
        add("subtitles.seekerdrones.deploying_station_launch", "Deploying Station launches");
        add("subtitles.seekerdrones.charging_station_dock", "Drone docks");
        add("subtitles.seekerdrones.programming_station_install", "Upgrade clicks in");
        add("message.seekerdrones.transmitter", "[%s] spotted %s at %s, %s, %s");

        add(DroneState.IDLE.getTranslationKey(), "Idle");
        add(DroneState.PATROLLING.getTranslationKey(), "Patrolling");
        add(DroneState.CHASING.getTranslationKey(), "Chasing");
        add(DroneState.FOLLOWING.getTranslationKey(), "Following");
        add(DroneState.RETURNING.getTranslationKey(), "Returning to charge");
        add(DroneState.CHARGING.getTranslationKey(), "Charging");

        add("screen.seekerdrones.drone_status", "Drone Status");
        add("screen.seekerdrones.drone_status.health", "Health");
        add("screen.seekerdrones.drone_status.health_value", "%s / %s");
        add("screen.seekerdrones.drone_status.health_hp", "%s HP");
        add("screen.seekerdrones.drone_status.energy_rate", "-%s");
        add("screen.seekerdrones.drone_status.energy_rate.tooltip", "Using about %s right now");
        add("screen.seekerdrones.drone_status.energy_rate.none", "Not using energy (not flying)");
        add("screen.seekerdrones.drone_status.sight", "Sight");
        add("screen.seekerdrones.drone_status.follow", "Follow");
        add("screen.seekerdrones.drone_status.sight.tooltip", "Sight range: %s blocks");
        add("screen.seekerdrones.drone_status.follow.tooltip", "Follow distance: %s blocks");
        add("screen.seekerdrones.drone_status.radar", "Radar");
        add("screen.seekerdrones.drone_status.radar.line", "Radius %s · %s");
        add("screen.seekerdrones.drone_status.radar.stationary", "Stationary");
        add("screen.seekerdrones.drone_status.radar.no_patrol", "No Patrol upgrade: the drone hovers in place.");
        add("screen.seekerdrones.drone_status.radar.preview", "A preview, not the drone's real position.");
        add("screen.seekerdrones.drone_status.patrol_center", "Patrol center: %s");
        add("screen.seekerdrones.drone_status.upgrades", "Upgrades");
        add("screen.seekerdrones.drone_status.upgrade", "%s ×%s");
        add("screen.seekerdrones.drone_status.targets", "Targets");
        add("screen.seekerdrones.target.kind.entity_type", "Entity type");
        add("screen.seekerdrones.target.kind.tag", "Entity tag");
        add("screen.seekerdrones.target.kind.player_name", "Player name");
        add("screen.seekerdrones.target.tag_cycles", "The preview cycles through the tag's members.");
        add("screen.seekerdrones.drone_status.none", "None");
        add("screen.seekerdrones.drone_status.not_set", "Not set");
        add("screen.seekerdrones.drone_status.not_deployed", "Not deployed");

        add("screen.seekerdrones.charging_station", "Charging Station");
        add("screen.seekerdrones.charging_station.repair_fluid.tooltip", "Repairs the docked drone");
        add("screen.seekerdrones.fluid_value", "%s / %s mB");

        add("screen.seekerdrones.drone_factory.operators", "Operators");
        add("screen.seekerdrones.drone_factory.empty", "Empty");
        add("screen.seekerdrones.drone_factory.fluid_value", "%s / %s mB");
        add("screen.seekerdrones.drone_factory.energy_use", "Uses %s while building");
        add("screen.seekerdrones.drone_factory.fluid_use", "This recipe needs %s");
        add("screen.seekerdrones.drone_factory.fluid_amount", "%s mB of %s");
        add("screen.seekerdrones.drone_factory.any_fluid", "any fluid");
        add(FactorySlots.Role.ROTOR.getTranslationKey(), "Rotor");
        add(FactorySlots.Role.ROTOR.getTranslationKey() + ".tooltip", "One per arm");
        add(FactorySlots.Role.CORE.getTranslationKey(), "Core");
        add(FactorySlots.Role.PLATING.getTranslationKey(), "Plating");
        add("screen.seekerdrones.drone_factory.takes", "Takes: %s");
        add("screen.seekerdrones.drone_factory.takes_count", "Takes: %s ×%s");
        add("screen.seekerdrones.drone_factory.unused_slot", "Not used by the loaded recipes");
        add(FactoryStatus.IDLE.getTranslationKey(), "Idle");
        add(FactoryStatus.IDLE.getHintKey(), "Put in the parts for a drone");
        add(FactoryStatus.BUILDING.getTranslationKey(), "Building");
        add(FactoryStatus.BUILDING.getHintKey(), "%s%% · %s");
        add(FactoryStatus.NO_ENERGY.getTranslationKey(), "Waiting for power");
        add(FactoryStatus.NO_ENERGY.getHintKey(), "Needs %s");
        add(FactoryStatus.NO_ENERGY.getHintKey() + ".unknown", "Needs more FE");
        add(FactoryStatus.MISSING_FLUID.getTranslationKey(), "Missing fluid");
        add(FactoryStatus.MISSING_FLUID.getHintKey(), "Needs %s");
        add(FactoryStatus.MISSING_FLUID.getHintKey() + ".unknown", "Fill the tank with the recipe's fluid");
        add(FactoryStatus.OUTPUT_FULL.getTranslationKey(), "Output full");
        add(FactoryStatus.OUTPUT_FULL.getHintKey(), "Take the drone out of the output");
        add("screen.seekerdrones.drone_factory.operators.owner", "Owner: %s (you)");
        add("screen.seekerdrones.drone_factory.operators.owner_only", "Owner only");
        add("screen.seekerdrones.drone_factory.operators.open", "Click to open");
        add("screen.seekerdrones.drone_factory.operators.close", "Click to close");
        add("screen.seekerdrones.drone_factory.operators.none", "No operators yet");
        add("screen.seekerdrones.drone_factory.operators.count_one", "1 operator");
        add("screen.seekerdrones.drone_factory.operators.count", "%s operators");
        add("screen.seekerdrones.drone_factory.operators.name", "Player name");
        add("screen.seekerdrones.drone_factory.operators.add", "Add");
        add("screen.seekerdrones.drone_factory.operators.add.tooltip", "Online or known players only");
        add("screen.seekerdrones.drone_factory.operators.add.enter", "Enter also adds");
        add("screen.seekerdrones.drone_factory.operators.remove_player", "Remove %s");
        add("screen.seekerdrones.drone_factory.operators.added", "Added %s.");
        add("screen.seekerdrones.drone_factory.operators.removed", "Removed %s.");
        add("screen.seekerdrones.drone_factory.operators.unknown_player", "Unknown player: %s");
        add("screen.seekerdrones.drone_factory.operators.already_operator", "%s is already an operator.");
        add("screen.seekerdrones.drone_factory.operators.not_operator", "%s is not an operator.");
        add("jei.seekerdrones.drone_assembly", "Drone Assembly");

        add("config.jade.plugin_seekerdrones.drone", "Drone Details");
        add("config.jade.plugin_seekerdrones.drone_energy", "Drone Energy");
        add("config.jade.plugin_seekerdrones.machine", "Machine Status");
        add("config.jade.plugin_seekerdrones.machine_progress", "Machine Progress");
        add("jade.seekerdrones.drone.id", "ID: %s");
        add("jade.seekerdrones.drone.state", "State: %s");
        add("jade.seekerdrones.drone.state_target", "State: %s %s");
        add("jade.seekerdrones.drone.owner", "Owner: %s");
        add("jade.seekerdrones.drone.targets", "Targets: %s");
        add("jade.seekerdrones.drone.targets.none", "Targets: none");
        add("jade.seekerdrones.programming_station.mode", "Mode: %s");
        add("jade.seekerdrones.programming_station.installing", "Installing %s");
        add("jade.seekerdrones.programming_station.reinsert", "Re-insert the drone to program it");
        add("jade.seekerdrones.programming_station.complete", "Complete");
        add("jade.seekerdrones.programming_station.extra_upgrades", "Drone has extra upgrades");
        add("jade.seekerdrones.programming_station.waiting", "Waiting for upgrades");
        add("jade.seekerdrones.deploying_station.auto_deploy_on", "Auto-deploy: On");
        add("jade.seekerdrones.charging_station.drone", "%s: %s");
        add("jei.seekerdrones.drone_assembly.time", "%s s");
        add("screen.seekerdrones.charging_station.energy", "Station energy");
        add("screen.seekerdrones.charging_station.charge_rate", "Charging the drone at %s");
        add("screen.seekerdrones.charging_station.owner", "Owner");
        add("screen.seekerdrones.charging_station.owner.value", "Owner: %s");
        add("screen.seekerdrones.charging_station.owner.tooltip", "Decides which drones may dock here");
        add("screen.seekerdrones.charging_station.no_drone", "No drone");
        add("screen.seekerdrones.charging_station.drone_energy", "Drone energy");
        add("screen.seekerdrones.charging_station.drone_health", "Drone health");
        add("screen.seekerdrones.charging_station.upgrades.effect", "Charge rate and capacity ×%s");
        add("screen.seekerdrones.upgrades", "Upgrades");
        add("screen.seekerdrones.upgrades.open", "Click to open");
        add("screen.seekerdrones.upgrades.close", "Click to close");
        add("screen.seekerdrones.upgrades.count", "%s: %s / %s");
        add("screen.seekerdrones.upgrades.value", "%s / %s");
        add("screen.seekerdrones.upgrades.slot", "%s Upgrade");
        add(StationStatusPayload.Status.IDLE.getTranslationKey(), "Idle");
        add(StationStatusPayload.Status.DOCKING.getTranslationKey(), "Drone docking");
        add(StationStatusPayload.Status.CHARGING.getTranslationKey(), "Charging");
        add(StationStatusPayload.Status.HEALING.getTranslationKey(), "Repairing");
        add(StationStatusPayload.Status.NO_POWER.getTranslationKey(), "Out of power");

        add(EnergyUnit.AUTO.getTranslationKey(), "Auto");
        add(EnergyUnit.FE.getTranslationKey(), "FE");
        add(EnergyUnit.JOULES.getTranslationKey(), "J");
        add(EnergyUnit.AUTO.getTranslationKey() + ".name", "Auto (Mekanism Joules)");
        add(EnergyUnit.FE.getTranslationKey() + ".name", "Forge Energy (FE)");
        add(EnergyUnit.JOULES.getTranslationKey() + ".name", "Mekanism Joules (J)");
        add("screen.seekerdrones.energy_unit.tooltip", "Energy unit: %s\nClick to change. Saved for you in this world.");

        add("message.seekerdrones.not_operator", "You are not an operator of this drone");

        add("commands.seekerdrones.not_holding_drone", "You must hold a drone item in your main hand");
        add("commands.seekerdrones.no_drones", "No drones matched");

        add("commands.seekerdrones.group.unknown", "Unknown operator group %s");
        add("commands.seekerdrones.group.single_owner", "The owner must be exactly one player");
        add("commands.seekerdrones.group.created", "Created operator group %s owned by %s");
        add("commands.seekerdrones.group.list.empty", "There are no operator groups");
        add("commands.seekerdrones.group.list.header", "%s operator group(s):");
        add("commands.seekerdrones.group.list.entry", "%s - owner %s, %s operator(s)");
        add("commands.seekerdrones.group.info", "Group %s - owner: %s, operators: %s");
        add("commands.seekerdrones.group.added", "Added %s operator(s) to group %s");
        add("commands.seekerdrones.group.removed", "Removed %s operator(s) from group %s");
        add("commands.seekerdrones.group.cannot_remove_owner", "%s is the group owner and can't be removed");
        add("commands.seekerdrones.group.assigned", "Assigned %s drone(s) to group %s");
        add("commands.seekerdrones.group.cleared", "Removed the operator group from %s drone(s)");

        add("commands.seekerdrones.config.unknown_tag", "Unknown entity tag #%s");
        add("commands.seekerdrones.config.duplicate_target", "%s is already a target");
        add("commands.seekerdrones.config.blacklisted_target", "%s is blacklisted on this server");
        add("commands.seekerdrones.config.no_such_index", "There is no target #%s (the drone has %s)");
        add("commands.seekerdrones.config.target.added", "Added target %s to %s drone(s)");
        add("commands.seekerdrones.config.target.removed", "Removed target #%s from %s drone(s)");
        add("commands.seekerdrones.config.target.cleared", "Cleared the targets of %s drone(s)");
        add("commands.seekerdrones.config.target.list.header", "%s - %s target(s), %s slot(s), follow distance %s:");
        add("commands.seekerdrones.config.target.list.empty", "  No targets");
        add("commands.seekerdrones.config.target.list.entry", "  %s. %s %s");
        add("commands.seekerdrones.config.target.list.ignored_slot", " (ignored: no free target slot)");
        add("commands.seekerdrones.config.target.list.ignored_player_seek", " (ignored: needs Player Seek)");
        add("commands.seekerdrones.config.target.list.ignored_blacklisted", " (ignored: blacklisted)");
        add("commands.seekerdrones.config.target.kind.entity_type", "Entity");
        add("commands.seekerdrones.config.target.kind.tag", "Tag");
        add("commands.seekerdrones.config.target.kind.player_name", "Player");
        add("commands.seekerdrones.config.followdistance.set", "Set the follow distance of %s drone(s) to %s");
        add("commands.seekerdrones.config.followdistance.too_large", "The follow distance can be at most %s");
        add("commands.seekerdrones.config.patrolcenter.set", "Set the patrol center of %s drone(s) to %s, %s, %s in %s");
        add("commands.seekerdrones.config.patrolcenter.cleared", "Cleared the patrol center of %s drone(s)");
        add("commands.seekerdrones.config.patrolradius.set", "Set the patrol radius of %s drone(s) to %s (capped by their Patrol upgrades)");
        add("commands.seekerdrones.config.patrolradius.cleared", "%s drone(s) now patrol at the largest radius their Patrol upgrades allow");
        add("commands.seekerdrones.config.patrolspeed.set", "Set the patrol speed of %s drone(s) to %s blocks/second (capped by their Patrol upgrades)");
        add("commands.seekerdrones.config.patrolspeed.cleared", "%s drone(s) now patrol at the base patrol speed");
        add("commands.seekerdrones.config.unknown_color", "Unknown color %s");
        add("commands.seekerdrones.config.color.set", "Set the color of %s drone(s) to %s");
        add("screen.seekerdrones.drone_status.patrol_radius", "Patrol radius: %s");
        add("screen.seekerdrones.drone_status.patrol_radius_value", "%s (max %s)");

        add("commands.seekerdrones.upgrade.unknown_type", "Unknown upgrade type %s");
        add("commands.seekerdrones.upgrade.over_type_cap", "A drone can have at most %2$s %1$s upgrade(s)");
        add("commands.seekerdrones.upgrade.over_total_slots", "That would use %s upgrade slots, but a drone has %s");
        add("commands.seekerdrones.upgrade.set", "Set %s upgrades to %s on %s drone(s)");
        add("commands.seekerdrones.upgrade.cleared", "Removed all upgrades from %s drone(s)");
        add("commands.seekerdrones.upgrade.list.header", "%s - %s / %s upgrade slots used:");
        add("commands.seekerdrones.upgrade.list.empty", "  No upgrades");
        add("commands.seekerdrones.upgrade.list.entry", "  %s x%s (max %s)");

        add("commands.seekerdrones.energy.set", "Set the energy of %s drone(s)");
        add("commands.seekerdrones.energy.get", "%s - %s");
    }
}
